FROM ubuntu:latest

LABEL MAINTAINER="jiangyuchao"
LABEL description="Nmap Patrowl Engine"
LABEL Version="1.0.0"

# 安装编译Nmap和engine-nmap所需的依赖项
RUN apt-get update \
    && apt-get install -y build-essential libssl-dev libpcap-dev libssh2-1-dev curl tar \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 下载、编译和安装 Nmap
RUN curl -OL https://nmap.org/dist/nmap-7.94.tar.bz2 \
    && tar xvf nmap-7.94.tar.bz2 \
    && cd nmap-7.94 \
    && ./configure \
    && make \
    && make install \
    && cd .. \
    && rm -rf nmap-7.94.tar.bz2 nmap-7.94 \
    && rm -rf /usr/local/share/nmap/scripts 

# Set the working directory
RUN mkdir -p /opt/patrowl-engines/nmap \
    && mkdir -p /opt/patrowl-engines/nmap/results \
    && mkdir -p /opt/patrowl-engines/nmap/logs 
WORKDIR /opt/patrowl-engines/nmap

# Copy the current directory contents into the container at /
COPY __init__.py engine-nmap.py requirements.txt README.md ./
COPY nmap.json.sample nmap.json
COPY libs/ libs/
# 后续增加scripts构建新的镜像，需要将这个文件夹内容进行调整
COPY scripts/ /usr/local/share/nmap/scripts

# 安装依赖项并清理缓存
RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-pip python3-dev gcc \
    && pip3 install --upgrade pip \
    && pip3 install --trusted-host pypi.python.org -r requirements.txt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# TCP端口
EXPOSE 6001

# 运行应用
CMD ["gunicorn", "engine-nmap:app", "-b", "0.0.0.0:6001", "--access-logfile", "-"]
